import fs from "fs";
import path from "path";

/** Shared, global demo screenshots/logo (generated by
 *  scripts/generate/create-demo-assets.mjs into assets/demo/, once for the whole
 *  app -- NOT per project). Used only as a render-time fallback so a freshly-applied
 *  template previews with real photo content before the user uploads their own
 *  screenshots. Never copied into, or registered as a source of, any individual
 *  project -- see resolveDemoAsset's call sites in render.ts/slots.ts. */
export const DEMO_ASSETS_DIR = path.join(process.cwd(), "assets", "demo");

export const DEMO_ASSET_SPECS: { id: string; file: string; width: number; height: number }[] = [
  ...Array.from({ length: 6 }, (_, i) => ({ id: `demo_${i + 1}`, file: `demo_screen_${i + 1}.png`, width: 1080, height: 2400 })),
  { id: "demo_landscape", file: "demo_landscape.png", width: 1920, height: 1080 },
  { id: "demo_logo", file: "demo_logo.png", width: 512, height: 512 },
];

const specById = new Map(DEMO_ASSET_SPECS.map((s) => [s.id, s]));

/** Resolves a demo source id to the shared global asset file, or undefined if the id
 *  isn't a demo id or the demo asset hasn't been generated yet (falls back further to
 *  the in-app SVG placeholder at each call site in that case). */
export function resolveDemoAsset(id: string | null | undefined): { absPath: string; width: number; height: number } | undefined {
  if (!id) return undefined;
  const spec = specById.get(id);
  if (!spec) return undefined;
  const absPath = path.join(DEMO_ASSETS_DIR, spec.file);
  if (!fs.existsSync(absPath)) return undefined;
  return { absPath, width: spec.width, height: spec.height };
}
